<-->f<-->l<-->o<-->w<-->c<-->h<-->a<-->r<-->t<--> <-->T<-->B<-->
<--> <--> <--> <--> <-->c<-->l<-->a<-->s<-->s<-->D<-->e<-->f<--> <-->f<-->r<-->o<-->n<-->t<-->e<-->n<-->d<--> <-->f<-->i<-->l<-->l<-->:<-->#<-->e<-->3<-->f<-->2<-->f<-->d<-->,<-->s<-->t<-->r<-->o<-->k<-->e<-->:<-->#<-->1<-->5<-->6<-->5<-->c<-->0<-->,<-->s<-->t<-->r<-->o<-->k<-->e<-->-<-->w<-->i<-->d<-->t<-->h<-->:<-->2<-->p<-->x<-->;<-->
<--> <--> <--> <--> <-->c<-->l<-->a<-->s<-->s<-->D<-->e<-->f<--> <-->b<-->a<-->c<-->k<-->e<-->n<-->d<--> <-->f<-->i<-->l<-->l<-->:<-->#<-->f<-->f<-->f<-->3<-->e<-->0<-->,<-->s<-->t<-->r<-->o<-->k<-->e<-->:<-->#<-->e<-->6<-->5<-->1<-->0<-->0<-->,<-->s<-->t<-->r<-->o<-->k<-->e<-->-<-->w<-->i<-->d<-->t<-->h<-->:<-->2<-->p<-->x<-->;<-->
<--> <--> <--> <--> <-->c<-->l<-->a<-->s<-->s<-->D<-->e<-->f<--> <-->e<-->x<-->t<--> <-->f<-->i<-->l<-->l<-->:<-->#<-->f<-->c<-->e<-->4<-->e<-->c<-->,<-->s<-->t<-->r<-->o<-->k<-->e<-->:<-->#<-->c<-->2<-->1<-->8<-->5<-->b<-->,<-->s<-->t<-->r<-->o<-->k<-->e<-->-<-->w<-->i<-->d<-->t<-->h<-->:<-->2<-->p<-->x<-->;<-->
<--> <--> <--> <--> <-->c<-->l<-->a<-->s<-->s<-->D<-->e<-->f<--> <-->d<-->b<--> <-->f<-->i<-->l<-->l<-->:<-->#<-->e<-->8<-->f<-->5<-->e<-->9<-->,<-->s<-->t<-->r<-->o<-->k<-->e<-->:<-->#<-->2<-->e<-->7<-->d<-->3<-->2<-->,<-->s<-->t<-->r<-->o<-->k<-->e<-->-<-->w<-->i<-->d<-->t<-->h<-->:<-->2<-->p<-->x<-->;<-->
<--> <--> <--> <--> <-->c<-->l<-->a<-->s<-->s<-->D<-->e<-->f<--> <-->i<-->n<-->f<-->r<-->a<--> <-->f<-->i<-->l<-->l<-->:<-->#<-->f<-->3<-->e<-->5<-->f<-->5<-->,<-->s<-->t<-->r<-->o<-->k<-->e<-->:<-->#<-->6<-->a<-->1<-->b<-->9<-->a<-->,<-->s<-->t<-->r<-->o<-->k<-->e<-->-<-->w<-->i<-->d<-->t<-->h<-->:<-->2<-->p<-->x<-->;<-->
<-->
<--> <--> <--> <--> <-->U<-->s<-->e<-->r<-->(<-->(<-->D<-->e<-->v<-->e<-->l<-->o<-->p<-->e<-->r<--> <-->C<-->l<-->i<-->e<-->n<-->t<-->)<-->)<-->:<-->:<-->:<-->e<-->x<-->t<-->
<--> <--> <--> <--> <-->G<-->u<-->e<-->s<-->t<-->(<-->(<-->C<-->o<-->l<-->l<-->a<-->b<--> <-->G<-->u<-->e<-->s<-->t<-->)<-->)<-->:<-->:<-->:<-->e<-->x<-->t<-->
<--> <--> <--> <--> <-->
<--> <--> <--> <--> <-->s<-->u<-->b<-->g<-->r<-->a<-->p<-->h<--> <-->P<-->r<-->e<-->s<-->e<-->n<-->t<-->a<-->t<-->i<-->o<-->n<-->_<-->L<-->a<-->y<-->e<-->r<--> <-->[<-->P<-->r<-->e<-->s<-->e<-->n<-->t<-->a<-->t<-->i<-->o<-->n<--> <-->/<--> <-->F<-->r<-->o<-->n<-->t<-->e<-->n<-->d<-->]<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->d<-->i<-->r<-->e<-->c<-->t<-->i<-->o<-->n<--> <-->L<-->R<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->U<-->I<-->[<-->M<-->a<-->i<-->n<--> <-->D<-->a<-->s<-->h<-->b<-->o<-->a<-->r<-->d<-->]<-->:<-->:<-->:<-->f<-->r<-->o<-->n<-->t<-->e<-->n<-->d<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->E<-->d<-->i<-->t<-->o<-->r<-->[<-->C<-->o<-->l<-->l<-->a<-->b<--> <-->C<-->o<-->d<-->e<--> <-->E<-->d<-->i<-->t<-->o<-->r<--> <-->(<-->M<-->o<-->n<-->a<-->c<-->o<-->/<-->Y<-->j<-->s<-->)<-->]<-->:<-->:<-->:<-->f<-->r<-->o<-->n<-->t<-->e<-->n<-->d<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->C<-->a<-->n<-->v<-->a<-->s<-->[<-->L<-->i<-->v<-->e<--> <-->W<-->h<-->i<-->t<-->e<-->b<-->o<-->a<-->r<-->d<-->]<-->:<-->:<-->:<-->f<-->r<-->o<-->n<-->t<-->e<-->n<-->d<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->V<-->i<-->d<-->e<-->o<-->U<-->I<-->[<-->W<-->e<-->b<-->R<-->T<-->C<--> <-->V<-->i<-->d<-->e<-->o<--> <-->C<-->h<-->a<-->t<-->]<-->:<-->:<-->:<-->f<-->r<-->o<-->n<-->t<-->e<-->n<-->d<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->A<-->I<-->C<-->h<-->a<-->t<-->[<-->A<-->I<--> <-->A<-->s<-->s<-->i<-->s<-->t<-->a<-->n<-->t<--> <-->C<-->h<-->a<-->t<-->b<-->o<-->x<-->]<-->:<-->:<-->:<-->f<-->r<-->o<-->n<-->t<-->e<-->n<-->d<-->
<--> <--> <--> <--> <-->e<-->n<-->d<-->
<--> <--> <--> <--> <-->
<--> <--> <--> <--> <-->s<-->u<-->b<-->g<-->r<-->a<-->p<-->h<--> <-->N<-->e<-->t<-->w<-->o<-->r<-->k<--> <-->[<-->A<-->P<-->I<--> <-->G<-->a<-->t<-->e<-->w<-->a<-->y<--> <-->&<--> <-->R<-->o<-->u<-->t<-->i<-->n<-->g<-->]<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->L<-->B<-->[<-->L<-->o<-->a<-->d<--> <-->B<-->a<-->l<-->a<-->n<-->c<-->e<-->r<--> <-->/<--> <-->N<-->g<-->i<-->n<-->x<-->]<-->:<-->:<-->:<-->i<-->n<-->f<-->r<-->a<-->
<--> <--> <--> <--> <-->e<-->n<-->d<-->
<--> <--> <--> <--> <-->
<--> <--> <--> <--> <-->s<-->u<-->b<-->g<-->r<-->a<-->p<-->h<--> <-->A<-->p<-->p<-->_<-->S<-->e<-->r<-->v<-->i<-->c<-->e<-->s<--> <-->[<-->A<-->p<-->p<-->l<-->i<-->c<-->a<-->t<-->i<-->o<-->n<--> <-->S<-->e<-->r<-->v<-->i<-->c<-->e<-->s<-->]<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->A<-->P<-->I<-->[<-->M<-->a<-->i<-->n<--> <-->R<-->E<-->S<-->T<--> <-->A<-->P<-->I<--> <-->(<-->N<-->e<-->x<-->t<-->.<-->j<-->s<--> <-->/<--> <-->E<-->x<-->p<-->r<-->e<-->s<-->s<-->)<-->]<-->:<-->:<-->:<-->b<-->a<-->c<-->k<-->e<-->n<-->d<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->W<-->S<-->S<-->[<-->W<-->e<-->b<-->S<-->o<-->c<-->k<-->e<-->t<--> <-->C<-->R<-->D<-->T<--> <-->S<-->e<-->r<-->v<-->e<-->r<--> <-->(<-->Y<-->j<-->s<--> <-->/<--> <-->s<-->o<-->c<-->k<-->e<-->t<-->.<-->i<-->o<-->)<-->]<-->:<-->:<-->:<-->b<-->a<-->c<-->k<-->e<-->n<-->d<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->S<-->i<-->g<-->n<-->a<-->l<-->i<-->n<-->g<-->[<-->W<-->e<-->b<-->R<-->T<-->C<--> <-->S<-->i<-->g<-->n<-->a<-->l<-->l<-->i<-->n<-->g<--> <-->S<-->e<-->r<-->v<-->e<-->r<-->]<-->:<-->:<-->:<-->b<-->a<-->c<-->k<-->e<-->n<-->d<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->L<-->L<-->M<-->P<-->r<-->o<-->x<-->y<-->[<-->A<-->I<--> <-->O<-->r<-->c<-->h<-->e<-->s<-->t<-->r<-->a<-->t<-->o<-->r<--> <-->A<-->P<-->I<-->]<-->:<-->:<-->:<-->b<-->a<-->c<-->k<-->e<-->n<-->d<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->E<-->x<-->e<-->c<-->P<-->r<-->o<-->x<-->y<-->[<-->S<-->a<-->n<-->d<-->b<-->o<-->x<--> <-->M<-->a<-->n<-->a<-->g<-->e<-->r<--> <-->A<-->P<-->I<-->]<-->:<-->:<-->:<-->b<-->a<-->c<-->k<-->e<-->n<-->d<-->
<--> <--> <--> <--> <-->e<-->n<-->d<-->
<--> <--> <--> <--> <-->
<--> <--> <--> <--> <-->s<-->u<-->b<-->g<-->r<-->a<-->p<-->h<--> <-->C<-->o<-->d<-->e<-->_<-->E<-->x<-->e<-->c<-->u<-->t<-->i<-->o<-->n<--> <-->[<-->S<-->e<-->c<-->u<-->r<-->e<--> <-->E<-->x<-->e<-->c<-->u<-->t<-->i<-->o<-->n<--> <-->E<-->n<-->v<-->i<-->r<-->o<-->n<-->m<-->e<-->n<-->t<-->]<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->D<-->o<-->c<-->k<-->e<-->r<-->[<-->(<-->I<-->s<-->o<-->l<-->a<-->t<-->e<-->d<--> <-->S<-->a<-->n<-->d<-->b<-->o<-->x<--> <-->C<-->o<-->n<-->t<-->a<-->i<-->n<-->e<-->r<-->s<-->)<-->]<-->:<-->:<-->:<-->i<-->n<-->f<-->r<-->a<-->
<--> <--> <--> <--> <-->e<-->n<-->d<-->
<--> <--> <--> <--> <-->
<--> <--> <--> <--> <-->s<-->u<-->b<-->g<-->r<-->a<-->p<-->h<--> <-->P<-->e<-->r<-->s<-->i<-->s<-->t<-->e<-->n<-->c<-->e<--> <-->[<-->D<-->a<-->t<-->a<--> <-->P<-->e<-->r<-->s<-->i<-->s<-->t<-->e<-->n<-->c<-->e<-->]<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->R<-->D<-->S<-->[<-->(<-->P<-->o<-->s<-->t<-->g<-->r<-->e<-->S<-->Q<-->L<--><<-->b<-->r<-->/<-->><-->A<-->u<-->t<-->h<-->,<--> <-->P<-->r<-->o<-->j<-->e<-->c<-->t<-->s<-->,<--> <-->L<-->o<-->g<-->s<-->)<-->]<-->:<-->:<-->:<-->d<-->b<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->B<-->l<-->o<-->b<-->[<-->(<-->O<-->b<-->j<-->e<-->c<-->t<--> <-->S<-->t<-->o<-->r<-->a<-->g<-->e<--><<-->b<-->r<-->/<-->><-->F<-->i<-->l<-->e<-->s<-->,<--> <-->A<-->v<-->a<-->t<-->a<-->r<-->s<-->,<--> <-->P<-->D<-->F<--> <-->E<-->x<-->p<-->o<-->r<-->t<-->s<-->)<-->]<-->:<-->:<-->:<-->d<-->b<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->R<-->e<-->d<-->i<-->s<-->[<-->(<-->R<-->e<-->d<-->i<-->s<--> <-->C<-->a<-->c<-->h<-->e<--><<-->b<-->r<-->/<-->><-->S<-->e<-->s<-->s<-->i<-->o<-->n<-->s<-->,<--> <-->R<-->a<-->t<-->e<--> <-->L<-->i<-->m<-->i<-->t<-->s<-->,<--> <-->S<-->t<-->a<-->t<-->e<-->)<-->]<-->:<-->:<-->:<-->d<-->b<-->
<--> <--> <--> <--> <-->e<-->n<-->d<-->
<--> <--> <--> <--> <-->
<--> <--> <--> <--> <-->s<-->u<-->b<-->g<-->r<-->a<-->p<-->h<--> <-->E<-->x<-->t<-->e<-->r<-->n<-->a<-->l<-->_<-->P<-->r<-->o<-->v<-->i<-->d<-->e<-->r<-->s<--> <-->[<-->E<-->x<-->t<-->e<-->r<-->n<-->a<-->l<--> <-->P<-->r<-->o<-->v<-->i<-->d<-->e<-->r<-->s<-->]<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->A<-->u<-->t<-->h<-->(<-->[<-->S<-->u<-->p<-->a<-->b<-->a<-->s<-->e<--> <-->/<--> <-->O<-->A<-->u<-->t<-->h<--> <-->I<-->D<-->P<-->]<-->)<-->:<-->:<-->:<-->e<-->x<-->t<-->
<--> <--> <--> <--> <--> <--> <--> <--> <-->L<-->L<-->M<-->s<-->(<-->[<-->E<-->x<-->t<-->e<-->r<-->n<-->a<-->l<--> <-->L<-->L<-->M<-->s<-->]<-->)<-->:<-->:<-->:<-->e<-->x<-->t<-->
<--> <--> <--> <--> <-->e<-->n<-->d<-->
<-->
<--> <--> <--> <--> <-->U<-->s<-->e<-->r<--> <-->-<-->-<-->><-->|<-->H<-->T<-->T<-->P<-->S<-->|<--> <-->L<-->B<-->
<--> <--> <--> <--> <-->G<-->u<-->e<-->s<-->t<--> <-->-<-->-<-->><-->|<-->H<-->T<-->T<-->P<-->S<--> <-->/<--> <-->W<-->S<-->S<-->|<--> <-->L<-->B<-->
<--> <--> <--> <--> <-->
<--> <--> <--> <--> <-->L<-->B<--> <-->-<-->-<-->><-->|<-->R<-->e<-->n<-->d<-->e<-->r<-->s<--> <-->U<-->I<-->|<--> <-->U<-->I<-->
<--> <--> <--> <--> <-->L<-->B<--> <-->-<-->-<-->><-->|<-->C<-->o<-->d<-->e<--> <-->S<-->y<-->n<-->c<--> <-->(<-->W<-->S<-->S<-->)<-->|<--> <-->W<-->S<-->S<-->
<--> <--> <--> <--> <-->L<-->B<--> <-->-<-->-<-->><-->|<-->C<-->a<-->n<-->v<-->a<-->s<--> <-->S<-->y<-->n<-->c<--> <-->(<-->W<-->S<-->S<-->)<-->|<--> <-->W<-->S<-->S<-->
<--> <--> <--> <--> <-->L<-->B<--> <-->-<-->-<-->><-->|<-->P<-->e<-->e<-->r<--> <-->s<-->i<-->g<-->n<-->a<-->l<--> <-->(<-->W<-->S<-->S<-->)<-->|<--> <-->S<-->i<-->g<-->n<-->a<-->l<-->i<-->n<-->g<-->
<--> <--> <--> <--> <-->L<-->B<--> <-->-<-->-<-->><-->|<-->S<-->t<-->a<-->n<-->d<-->a<-->r<-->d<--> <-->r<-->e<-->q<-->s<-->|<--> <-->A<-->P<-->I<-->
<--> <--> <--> <--> <-->
<--> <--> <--> <--> <-->U<-->I<--> <-->-<-->-<-->><--> <-->E<-->d<-->i<-->t<-->o<-->r<-->
<--> <--> <--> <--> <-->U<-->I<--> <-->-<-->-<-->><--> <-->C<-->a<-->n<-->v<-->a<-->s<-->
<--> <--> <--> <--> <-->U<-->I<--> <-->-<-->-<-->><--> <-->V<-->i<-->d<-->e<-->o<-->U<-->I<-->
<--> <--> <--> <--> <-->U<-->I<--> <-->-<-->-<-->><--> <-->A<-->I<-->C<-->h<-->a<-->t<-->
<--> <--> <--> <--> <-->
<--> <--> <--> <--> <-->A<-->P<-->I<--> <-->-<-->-<-->><-->|<-->A<-->u<-->t<-->h<-->o<-->r<-->i<-->z<-->e<--> <-->T<-->o<-->k<-->e<-->n<-->|<--> <-->A<-->u<-->t<-->h<-->
<--> <--> <--> <--> <-->A<-->P<-->I<--> <-->-<-->-<-->><-->|<-->R<-->e<-->a<-->d<-->/<-->W<-->r<-->i<-->t<-->e<-->|<--> <-->R<-->D<-->S<-->
<--> <--> <--> <--> <-->A<-->P<-->I<--> <-->-<-->-<-->><-->|<-->S<-->e<-->r<-->v<-->e<-->/<-->S<-->a<-->v<-->e<--> <-->B<-->l<-->o<-->b<-->s<-->|<--> <-->B<-->l<-->o<-->b<-->
<--> <--> <--> <--> <-->A<-->P<-->I<--> <-->-<-->-<-->><-->|<-->C<-->h<-->e<-->c<-->k<--> <-->Q<-->u<-->o<-->t<-->a<-->s<-->|<--> <-->R<-->e<-->d<-->i<-->s<-->
<-->
<--> <--> <--> <--> <-->W<-->S<-->S<--> <-->-<-->-<-->><-->|<-->P<-->e<-->r<-->s<-->i<-->s<-->t<--> <-->D<-->o<-->c<-->u<-->m<-->e<-->n<-->t<--> <-->S<-->t<-->a<-->t<-->e<-->|<--> <-->R<-->D<-->S<-->
<--> <--> <--> <--> <-->S<-->i<-->g<-->n<-->a<-->l<-->i<-->n<-->g<--> <-->-<-->-<-->><-->|<-->M<-->a<-->n<-->a<-->g<-->e<--> <-->R<-->o<-->o<-->m<-->s<-->|<--> <-->R<-->e<-->d<-->i<-->s<-->
<--> <--> <--> <--> <-->
<--> <--> <--> <--> <-->A<-->P<-->I<--> <-->-<-->-<-->><-->|<-->R<-->u<-->n<--> <-->R<-->e<-->q<-->u<-->e<-->s<-->t<-->|<--> <-->E<-->x<-->e<-->c<-->P<-->r<-->o<-->x<-->y<-->
<--> <--> <--> <--> <-->E<-->x<-->e<-->c<-->P<-->r<-->o<-->x<-->y<--> <-->-<-->-<-->><-->|<-->S<-->p<-->a<-->w<-->n<-->s<--> <-->e<-->n<-->v<--> <-->&<--> <-->r<-->u<-->n<-->s<-->|<--> <-->D<-->o<-->c<-->k<-->e<-->r<-->
<--> <--> <--> <--> <-->
<--> <--> <--> <--> <-->A<-->P<-->I<--> <-->-<-->-<-->><-->|<-->P<-->r<-->o<-->m<-->p<-->t<--> <-->R<-->e<-->q<-->u<-->e<-->s<-->t<-->|<--> <-->L<-->L<-->M<-->P<-->r<-->o<-->x<-->y<-->
<--> <--> <--> <--> <-->L<-->L<-->M<-->P<-->r<-->o<-->x<-->y<--> <-->-<-->-<-->><-->|<-->F<-->o<-->r<-->w<-->a<-->r<-->d<-->s<--> <-->s<-->t<-->r<-->e<-->a<-->m<-->|<--> <-->L<-->L<-->M<-->s<-->
<-->