// Meeting types - shared between video call hook and PDF generator

export interface Participant {
  id: string;
  username: string;
  color: string;
  stream?: MediaStream;
  isAudioEnabled: boolean;
  isVideoEnabled: boolean;
  isScreenSharing: boolean;
  joinedAt: Date;
  leftAt?: Date;
}

export interface FileActivity {
  id: string;
  type: 'created' | 'updated' | 'deleted';
  fileName: string;
  userId: string;
  username: string;
  timestamp: Date;
  details?: string;
}

export interface MeetingNote {
  id: string;
  content: string;
  author: string;
  authorId: string;
  timestamp: Date;
  isAutoGenerated: boolean;
}

export interface MeetingData {
  id: string;
  title: string;
  hostId: string;
  hostName: string;
  startTime: Date;
  endTime?: Date;
  participants: Participant[];
  fileActivities: FileActivity[];
  notes: MeetingNote[];
  chatMessages: { userId: string; username: string; message: string; timestamp: Date }[];
}
