import { useState, useEffect, useCallback, useRef } from 'react';
import { io, Socket } from 'socket.io-client';
import type { Participant, FileActivity, MeetingNote, MeetingData } from '../types/meeting';
import { SOCKET_URL } from '@/config/api';

// Re-export types for convenience
export type { Participant, FileActivity, MeetingNote, MeetingData };

export function useVideoCall(sessionId: string | null) {
  const [localStream, setLocalStream] = useState<MediaStream | null>(null);
  const [screenStream, setScreenStream] = useState<MediaStream | null>(null);
  const [participants, setParticipants] = useState<Map<string, Participant>>(new Map());
  const [isAudioEnabled, setIsAudioEnabled] = useState(true);
  const [isVideoEnabled, setIsVideoEnabled] = useState(true);
  const [isScreenSharing, setIsScreenSharing] = useState(false);
  const [isInCall, setIsInCall] = useState(false);
  const [meetingData, setMeetingData] = useState<MeetingData | null>(null);
  
  const peerConnections = useRef<Map<string, RTCPeerConnection>>(new Map());
  const socketRef = useRef<Socket | null>(null);
  const localVideoRef = useRef<HTMLVideoElement | null>(null);
  const localStreamRef = useRef<MediaStream | null>(null);

  const ICE_SERVERS = {
    iceServers: [
      { urls: 'stun:stun.l.google.com:19302' },
      { urls: 'stun:stun1.l.google.com:19302' },
    ]
  };

  // Initialize meeting data
  const initializeMeeting = useCallback((hostId: string, hostName: string, title: string = 'Collaboration Session') => {
    const meeting: MeetingData = {
      id: `meeting-${Date.now()}`,
      title,
      hostId,
      hostName,
      startTime: new Date(),
      participants: [],
      fileActivities: [],
      notes: [],
      chatMessages: []
    };
    setMeetingData(meeting);
    
    // Add auto-generated note for meeting start
    addNote(`Meeting "${title}" started by ${hostName}`, 'System', 'system', true);
    
    return meeting;
  }, []);

  // Add meeting note
  const addNote = useCallback((content: string, author: string, authorId: string, isAutoGenerated: boolean = false) => {
    const note: MeetingNote = {
      id: `note-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      content,
      author,
      authorId,
      timestamp: new Date(),
      isAutoGenerated
    };
    
    setMeetingData(prev => {
      if (!prev) return prev;
      return { ...prev, notes: [...prev.notes, note] };
    });
    
    return note;
  }, []);

  // Track file activity
  const trackFileActivity = useCallback((
    type: 'created' | 'updated' | 'deleted',
    fileName: string,
    userId: string,
    username: string,
    details?: string
  ) => {
    const activity: FileActivity = {
      id: `activity-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      type,
      fileName,
      userId,
      username,
      timestamp: new Date(),
      details
    };
    
    setMeetingData(prev => {
      if (!prev) return prev;
      return { ...prev, fileActivities: [...prev.fileActivities, activity] };
    });
    
    // Auto-generate note for file activity
    const actionText = type === 'created' ? 'created' : type === 'updated' ? 'modified' : 'deleted';
    addNote(`${username} ${actionText} file: ${fileName}`, 'System', 'system', true);
    
    return activity;
  }, [addNote]);

  // Start local media stream
  const startLocalStream = useCallback(async (video: boolean = true, audio: boolean = true) => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: video ? { width: 1280, height: 720, facingMode: 'user' } : false,
        audio: audio ? { echoCancellation: true, noiseSuppression: true } : false
      });
      
      localStreamRef.current = stream;
      setLocalStream(stream);
      setIsVideoEnabled(video);
      setIsAudioEnabled(audio);
      
      if (localVideoRef.current) {
        localVideoRef.current.srcObject = stream;
      }
      
      return stream;
    } catch (error: any) {
      // User denied camera/mic permission - try audio only
      if (error.name === 'NotAllowedError' && video) {
        console.log('Camera permission denied, trying audio only');
        try {
          const audioStream = await navigator.mediaDevices.getUserMedia({ audio: true, video: false });
          setLocalStream(audioStream);
          setIsVideoEnabled(false);
          setIsAudioEnabled(true);
          return audioStream;
        } catch {
          console.log('Audio permission also denied');
        }
      }
      console.error('Error accessing media devices:', error);
      return null;
    }
  }, []);

  // Start screen sharing
  const startScreenShare = useCallback(async () => {
    try {
      const stream = await navigator.mediaDevices.getDisplayMedia({
        video: { cursor: 'always' } as any,
        audio: true
      });
      
      setScreenStream(stream);
      setIsScreenSharing(true);
      
      // Handle when user stops sharing via browser UI
      stream.getVideoTracks()[0].onended = () => {
        stopScreenShare();
      };
      
      // Notify other participants
      if (socketRef.current && sessionId) {
        socketRef.current.emit('screen-share-started', { sessionId });
      }
      
      // Add note
      addNote('Screen sharing started', 'System', 'system', true);
      
      return stream;
    } catch (error: any) {
      // User cancelled the screen share dialog - this is expected behavior
      if (error.name === 'NotAllowedError') {
        console.log('Screen share cancelled by user');
        return null;
      }
      console.error('Error starting screen share:', error);
      return null;
    }
  }, [sessionId, addNote]);

  // Stop screen sharing
  const stopScreenShare = useCallback(() => {
    if (screenStream) {
      screenStream.getTracks().forEach(track => track.stop());
      setScreenStream(null);
      setIsScreenSharing(false);
      
      if (socketRef.current && sessionId) {
        socketRef.current.emit('screen-share-stopped', { sessionId });
      }
      
      addNote('Screen sharing stopped', 'System', 'system', true);
    }
  }, [screenStream, sessionId, addNote]);

  // Toggle audio
  const toggleAudio = useCallback(() => {
    if (localStreamRef.current) {
      const audioTrack = localStreamRef.current.getAudioTracks()[0];
      if (audioTrack) {
        audioTrack.enabled = !audioTrack.enabled;
        setIsAudioEnabled(audioTrack.enabled);
        
        // Notify other participants
        if (socketRef.current && sessionId) {
          socketRef.current.emit('toggle-audio', {
            sessionId,
            isEnabled: audioTrack.enabled
          });
        }
      }
    }
  }, [sessionId]);

  // Toggle video
  const toggleVideo = useCallback(() => {
    if (localStreamRef.current) {
      const videoTrack = localStreamRef.current.getVideoTracks()[0];
      if (videoTrack) {
        videoTrack.enabled = !videoTrack.enabled;
        setIsVideoEnabled(videoTrack.enabled);
        
        // Notify other participants
        if (socketRef.current && sessionId) {
          socketRef.current.emit('toggle-video', {
            sessionId,
            isEnabled: videoTrack.enabled
          });
        }
      }
    }
  }, [sessionId]);


  // Create peer connection for a participant
  const createPeerConnection = useCallback((participantId: string, participantName: string, stream: MediaStream | null) => {
    const pc = new RTCPeerConnection(ICE_SERVERS);
    
    // Add local tracks to connection
    if (stream) {
      stream.getTracks().forEach(track => {
        console.log(`Adding ${track.kind} track to peer connection for ${participantName}`);
        pc.addTrack(track, stream);
      });
    }
    
    // Handle incoming tracks
    pc.ontrack = (event) => {
      console.log(`Received ${event.track.kind} track from ${participantName}`, event.streams[0]);
      const remoteStream = event.streams[0];
      
      setParticipants(prev => {
        const updated = new Map(prev);
        const participant = updated.get(participantId);
        if (participant) {
          updated.set(participantId, { ...participant, stream: remoteStream });
        } else {
          // Create participant if doesn't exist
          updated.set(participantId, {
            id: participantId,
            username: participantName,
            color: '#4ECDC4',
            stream: remoteStream,
            isAudioEnabled: true,
            isVideoEnabled: true,
            isScreenSharing: false,
            joinedAt: new Date()
          });
        }
        return updated;
      });
    };
    
    // Handle connection state changes
    pc.onconnectionstatechange = () => {
      console.log(`Connection state with ${participantName}: ${pc.connectionState}`);
    };
    
    pc.oniceconnectionstatechange = () => {
      console.log(`ICE connection state with ${participantName}: ${pc.iceConnectionState}`);
    };
    
    // Handle ICE candidates
    pc.onicecandidate = (event) => {
      if (event.candidate && socketRef.current) {
        socketRef.current.emit('ice-candidate', {
          sessionId,
          targetId: participantId,
          candidate: event.candidate
        });
      }
    };
    
    peerConnections.current.set(participantId, pc);
    return pc;
  }, [sessionId]);

  // Join video call
  const joinCall = useCallback(async (userId: string, username: string, userColor: string) => {
    try {
      const stream = await startLocalStream();
      if (!stream) {
        throw new Error('Failed to get media stream');
      }
      
      setIsInCall(true);
      
      // Add self to participants
      const selfParticipant: Participant = {
        id: userId,
        username,
        color: userColor,
        stream: stream,
        isAudioEnabled: true,
        isVideoEnabled: true,
        isScreenSharing: false,
        joinedAt: new Date()
      };
      
      setParticipants(prev => {
        const updated = new Map(prev);
        updated.set(userId, selfParticipant);
        return updated;
      });
      
      // Update meeting data
      setMeetingData(prev => {
        if (!prev) return prev;
        return {
          ...prev,
          participants: [...prev.participants, selfParticipant]
        };
      });
      
      addNote(`${username} joined the call`, 'System', 'system', true);
      
      // Notify server
      if (socketRef.current && sessionId) {
        socketRef.current.emit('join-video-call', {
          sessionId,
          userId,
          username,
          color: userColor
        });
      }
    } catch (error) {
      console.error('Error joining call:', error);
      throw error;
    }
  }, [startLocalStream, sessionId, addNote]);

  // Leave video call
  const leaveCall = useCallback((userId: string, username: string) => {
    // Stop all tracks
    if (localStreamRef.current) {
      localStreamRef.current.getTracks().forEach(track => track.stop());
      localStreamRef.current = null;
      setLocalStream(null);
    }
    
    if (screenStream) {
      screenStream.getTracks().forEach(track => track.stop());
      setScreenStream(null);
    }
    
    // Close all peer connections
    peerConnections.current.forEach(pc => pc.close());
    peerConnections.current.clear();
    
    // Update participant leave time
    setMeetingData(prev => {
      if (!prev) return prev;
      const updatedParticipants = prev.participants.map(p => 
        p.id === userId ? { ...p, leftAt: new Date() } : p
      );
      return { ...prev, participants: updatedParticipants };
    });
    
    addNote(`${username} left the call`, 'System', 'system', true);
    
    setIsInCall(false);
    setParticipants(new Map());
    
    // Notify server
    if (socketRef.current && sessionId) {
      socketRef.current.emit('leave-video-call', { sessionId, userId });
    }
  }, [screenStream, sessionId, addNote]);

  // End meeting (host only)
  const endMeeting = useCallback(() => {
    setMeetingData(prev => {
      if (!prev) return prev;
      return { ...prev, endTime: new Date() };
    });
    
    addNote('Meeting ended', 'System', 'system', true);
    
    // Notify all participants
    if (socketRef.current && sessionId) {
      socketRef.current.emit('end-meeting', { sessionId });
    }
  }, [sessionId, addNote]);

  // Add chat message to meeting data
  const addChatMessage = useCallback((userId: string, username: string, message: string) => {
    setMeetingData(prev => {
      if (!prev) return prev;
      return {
        ...prev,
        chatMessages: [...prev.chatMessages, { userId, username, message, timestamp: new Date() }]
      };
    });
  }, []);

  // Setup socket listeners
  useEffect(() => {
    if (!sessionId) return;
    
    const socket = io(SOCKET_URL, {
      auth: { token: localStorage.getItem('devmindx_token') },
      transports: ['websocket', 'polling']
    });
    
    socketRef.current = socket;
    
    socket.on('connect', () => {
      console.log('Video call socket connected:', socket.id);
    });
    
    socket.on('connect_error', (error) => {
      console.error('Video call socket connection error:', error);
    });
    
    // Handle new participant joining
    socket.on('participant-joined-call', async (data: { userId: string; username: string; color: string }) => {
      console.log(`[VIDEO CALL] Participant ${data.username} (${data.userId}) joined call`);
      
      const participant: Participant = {
        id: data.userId,
        username: data.username,
        color: data.color,
        isAudioEnabled: true,
        isVideoEnabled: true,
        isScreenSharing: false,
        joinedAt: new Date()
      };
      
      setParticipants(prev => {
        const updated = new Map(prev);
        updated.set(data.userId, participant);
        console.log(`[VIDEO CALL] Total participants now: ${updated.size}`);
        return updated;
      });
      
      // Use ref to get current stream (not stale state)
      const currentStream = localStreamRef.current;
      if (!currentStream) {
        console.error('[VIDEO CALL] No local stream available to create peer connection');
        return;
      }
      
      console.log(`[VIDEO CALL] Creating peer connection for ${data.username}`);
      console.log(`[VIDEO CALL] Local stream tracks:`, currentStream.getTracks().map(t => `${t.kind}: ${t.enabled}`));
      
      // Create peer connection and send offer
      const pc = createPeerConnection(data.userId, data.username, currentStream);
      try {
        const offer = await pc.createOffer({
          offerToReceiveAudio: true,
          offerToReceiveVideo: true
        });
        await pc.setLocalDescription(offer);
        
        console.log(`[VIDEO CALL] Sending offer to ${data.username}`);
        socket.emit('video-offer', {
          sessionId,
          targetId: data.userId,
          offer
        });
      } catch (error) {
        console.error('[VIDEO CALL] Error creating offer:', error);
      }
    });
    
    // Handle video offer
    socket.on('video-offer', async (data: { senderId: string; senderName: string; offer: RTCSessionDescriptionInit }) => {
      console.log(`[VIDEO CALL] Received video offer from ${data.senderName} (${data.senderId})`);
      
      // Use ref to get current stream (not stale state)
      const currentStream = localStreamRef.current;
      if (!currentStream) {
        console.error('[VIDEO CALL] No local stream available to answer offer');
        return;
      }
      
      console.log(`[VIDEO CALL] Creating peer connection to answer ${data.senderName}`);
      console.log(`[VIDEO CALL] Local stream tracks:`, currentStream.getTracks().map(t => `${t.kind}: ${t.enabled}`));
      
      const pc = createPeerConnection(data.senderId, data.senderName, currentStream);
      try {
        await pc.setRemoteDescription(new RTCSessionDescription(data.offer));
        const answer = await pc.createAnswer();
        await pc.setLocalDescription(answer);
        
        console.log(`[VIDEO CALL] Sending answer to ${data.senderName}`);
        socket.emit('video-answer', {
          sessionId,
          targetId: data.senderId,
          answer
        });
      } catch (error) {
        console.error('[VIDEO CALL] Error handling video offer:', error);
      }
    });
    
    // Handle video answer
    socket.on('video-answer', async (data: { senderId: string; answer: RTCSessionDescriptionInit }) => {
      console.log(`[VIDEO CALL] Received video answer from ${data.senderId}`);
      const pc = peerConnections.current.get(data.senderId);
      if (pc) {
        try {
          await pc.setRemoteDescription(new RTCSessionDescription(data.answer));
          console.log(`[VIDEO CALL] Set remote description for ${data.senderId}`);
        } catch (error) {
          console.error('[VIDEO CALL] Error setting remote description:', error);
        }
      } else {
        console.error(`[VIDEO CALL] No peer connection found for ${data.senderId}`);
      }
    });
    
    // Handle ICE candidate
    socket.on('ice-candidate', async (data: { senderId: string; candidate: RTCIceCandidateInit }) => {
      console.log(`[VIDEO CALL] Received ICE candidate from ${data.senderId}`);
      const pc = peerConnections.current.get(data.senderId);
      if (pc) {
        try {
          await pc.addIceCandidate(new RTCIceCandidate(data.candidate));
          console.log(`[VIDEO CALL] Added ICE candidate for ${data.senderId}`);
        } catch (error) {
          console.error('[VIDEO CALL] Error adding ICE candidate:', error);
        }
      } else {
        console.error(`[VIDEO CALL] No peer connection found for ICE candidate from ${data.senderId}`);
      }
    });
    
    // Handle participant leaving
    socket.on('participant-left-call', (data: { userId: string }) => {
      const pc = peerConnections.current.get(data.userId);
      if (pc) {
        pc.close();
        peerConnections.current.delete(data.userId);
      }
      
      setParticipants(prev => {
        const updated = new Map(prev);
        updated.delete(data.userId);
        return updated;
      });
    });
    
    // Handle audio toggle
    socket.on('participant-audio-toggled', (data: { userId: string; isEnabled: boolean }) => {
      setParticipants(prev => {
        const updated = new Map(prev);
        const participant = updated.get(data.userId);
        if (participant) {
          updated.set(data.userId, { ...participant, isAudioEnabled: data.isEnabled });
        }
        return updated;
      });
    });
    
    // Handle video toggle
    socket.on('participant-video-toggled', (data: { userId: string; isEnabled: boolean }) => {
      setParticipants(prev => {
        const updated = new Map(prev);
        const participant = updated.get(data.userId);
        if (participant) {
          updated.set(data.userId, { ...participant, isVideoEnabled: data.isEnabled });
        }
        return updated;
      });
    });
    
    // Handle meeting ended
    socket.on('meeting-ended', () => {
      endMeeting();
    });
    
    return () => {
      socket.close();
    };
  }, [sessionId, createPeerConnection, endMeeting]);

  return {
    // State
    localStream,
    screenStream,
    participants,
    isAudioEnabled,
    isVideoEnabled,
    isScreenSharing,
    isInCall,
    meetingData,
    localVideoRef,
    
    // Actions
    initializeMeeting,
    joinCall,
    leaveCall,
    endMeeting,
    toggleAudio,
    toggleVideo,
    startScreenShare,
    stopScreenShare,
    addNote,
    trackFileActivity,
    addChatMessage
  };
}
