import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Loader2, CheckCircle, XCircle, ExternalLink } from 'lucide-react';

export default function SandboxTest() {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);

  const testCodeSandbox = async () => {
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const response = await fetch('/api/preview/create', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('devmindx_token')}`,
        },
        body: JSON.stringify({
          files: {
            'index.html': `<!DOCTYPE html>
<html>
<head>
  <title>CodeSandbox Test</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      display: flex;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    }
    .container {
      text-align: center;
      padding: 3rem;
      background: rgba(255, 255, 255, 0.95);
      border-radius: 20px;
      box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
      max-width: 500px;
    }
    h1 {
      color: #667eea;
      margin: 0 0 1rem 0;
      font-size: 2.5rem;
      animation: bounce 2s infinite;
    }
    @keyframes bounce {
      0%, 100% { transform: translateY(0); }
      50% { transform: translateY(-10px); }
    }
    p {
      color: #666;
      font-size: 1.2rem;
      margin: 1rem 0;
    }
    .time {
      font-size: 2rem;
      color: #764ba2;
      font-weight: bold;
      margin: 1rem 0;
    }
    button {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      border: none;
      padding: 1rem 2rem;
      font-size: 1.1rem;
      border-radius: 10px;
      cursor: pointer;
      font-weight: bold;
      margin-top: 1rem;
      transition: transform 0.2s;
    }
    button:hover {
      transform: scale(1.05);
    }
    .counter {
      font-size: 3rem;
      color: #667eea;
      font-weight: bold;
      margin: 1rem 0;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>🎉 CodeSandbox Works!</h1>
    <p>This is a live preview powered by CodeSandbox API</p>
    <div class="time" id="time"></div>
    <div class="counter" id="counter">0</div>
    <button onclick="incrementCounter()">Click Me!</button>
    <p style="font-size: 0.9rem; color: #999; margin-top: 2rem;">
      Generated by DevMindX
    </p>
  </div>
  
  <script>
    let count = 0;
    
    function incrementCounter() {
      count++;
      document.getElementById('counter').textContent = count;
    }
    
    function updateTime() {
      const now = new Date();
      document.getElementById('time').textContent = now.toLocaleTimeString();
    }
    
    updateTime();
    setInterval(updateTime, 1000);
  </script>
</body>
</html>`
          },
          template: 'static',
          title: 'DevMindX CodeSandbox Test',
          description: 'Testing CodeSandbox integration'
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Failed to create sandbox');
      }

      const data = await response.json();
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-900 p-8">
      <div className="max-w-4xl mx-auto">
        <Card className="p-8 bg-gray-800 border-gray-700">
          <h1 className="text-3xl font-bold text-white mb-4">
            🧪 CodeSandbox Integration Test
          </h1>
          <p className="text-gray-400 mb-6">
            This page tests the CodeSandbox API integration directly without using AI generation.
          </p>

          <Button
            onClick={testCodeSandbox}
            disabled={loading}
            className="bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700"
          >
            {loading ? (
              <>
                <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                Creating Sandbox...
              </>
            ) : (
              'Test CodeSandbox'
            )}
          </Button>

          {error && (
            <div className="mt-6 p-4 bg-red-500/10 border border-red-500/30 rounded-lg">
              <div className="flex items-start space-x-3">
                <XCircle className="w-6 h-6 text-red-400 flex-shrink-0 mt-0.5" />
                <div>
                  <h3 className="text-red-400 font-semibold mb-1">Error</h3>
                  <p className="text-red-300 text-sm">{error}</p>
                </div>
              </div>
            </div>
          )}

          {result && (
            <div className="mt-6 space-y-4">
              <div className="p-4 bg-green-500/10 border border-green-500/30 rounded-lg">
                <div className="flex items-start space-x-3">
                  <CheckCircle className="w-6 h-6 text-green-400 flex-shrink-0 mt-0.5" />
                  <div>
                    <h3 className="text-green-400 font-semibold mb-1">Success!</h3>
                    <p className="text-green-300 text-sm">CodeSandbox created successfully</p>
                  </div>
                </div>
              </div>

              <div className="bg-gray-900 rounded-lg p-4 space-y-3">
                <div>
                  <label className="text-gray-400 text-sm">Sandbox ID:</label>
                  <p className="text-white font-mono text-sm">{result.sandboxId}</p>
                </div>
                
                <div>
                  <label className="text-gray-400 text-sm">Preview URL:</label>
                  <div className="flex items-center space-x-2">
                    <p className="text-blue-400 font-mono text-sm break-all">{result.previewUrl}</p>
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={() => window.open(result.previewUrl, '_blank')}
                    >
                      <ExternalLink className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
                
                <div>
                  <label className="text-gray-400 text-sm">Editor URL:</label>
                  <div className="flex items-center space-x-2">
                    <p className="text-blue-400 font-mono text-sm break-all">{result.editorUrl}</p>
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={() => window.open(result.editorUrl, '_blank')}
                    >
                      <ExternalLink className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              </div>

              <div className="bg-gray-950 rounded-lg overflow-hidden" style={{ height: '600px' }}>
                <iframe
                  src={result.previewUrl}
                  className="w-full h-full border-0"
                  title="CodeSandbox Preview"
                  sandbox="allow-scripts allow-same-origin"
                />
              </div>
            </div>
          )}
        </Card>
      </div>
    </div>
  );
}
