import axios from 'axios';

const CODESANDBOX_API_URL = 'https://codesandbox.io/api/v1';
const API_TOKEN = process.env.CODESANDBOX_API_TOKEN;
const API_VERSION = process.env.CODESANDBOX_API_VERSION || '2023-07-01';

interface SandboxFile {
  content: string;
  isBinary?: boolean;
}

interface SandboxFiles {
  [path: string]: SandboxFile;
}

interface CreateSandboxParams {
  files: { [path: string]: string };
  template?: 'react' | 'vue' | 'angular' | 'node' | 'static' | 'vanilla';
  title?: string;
  description?: string;
}

interface SandboxResponse {
  sandboxId: string;
  previewUrl: string;
  editorUrl: string;
}

class CodeSandboxService {
  private apiToken: string;
  private headers: Record<string, string>;

  constructor() {
    if (!API_TOKEN) {
      throw new Error('CODESANDBOX_API_TOKEN is not configured');
    }
    this.apiToken = API_TOKEN;
    this.headers = {
      'Authorization': `Bearer ${this.apiToken}`,
      'Content-Type': 'application/json',
      'X-API-Version': API_VERSION,
    };
  }

  /**
   * Create a new sandbox with the provided files
   */
  async createSandbox(params: CreateSandboxParams): Promise<SandboxResponse> {
    try {
      const { files, template = 'react', title, description } = params;

      // Convert files to CodeSandbox format
      const sandboxFiles: SandboxFiles = {};
      
      for (const [path, content] of Object.entries(files)) {
        sandboxFiles[path] = {
          content,
          isBinary: false,
        };
      }

      // Add package.json if not present and template requires it
      if (!sandboxFiles['package.json'] && template !== 'static') {
        sandboxFiles['package.json'] = {
          content: JSON.stringify(this.getDefaultPackageJson(template, title), null, 2),
        };
      }

      const payload = {
        files: sandboxFiles,
        template,
        title: title || 'DevMindX Generated Project',
        description: description || 'Generated by DevMindX AI',
      };

      console.log('Creating CodeSandbox with payload:', JSON.stringify(payload, null, 2).substring(0, 500));

      const response = await axios.post(
        `${CODESANDBOX_API_URL}/sandboxes/define?json=1`,
        payload,
        { headers: this.headers }
      );

      console.log('CodeSandbox API response:', response.data);

      const sandboxId = response.data.sandbox_id || response.data.id;

      if (!sandboxId) {
        console.error('No sandbox ID in response:', response.data);
        throw new Error('CodeSandbox API did not return a sandbox ID');
      }

      return {
        sandboxId,
        previewUrl: `https://${sandboxId}.csb.app`,
        editorUrl: `https://codesandbox.io/s/${sandboxId}`,
      };
    } catch (error) {
      console.error('Error creating CodeSandbox:', error);
      if (axios.isAxiosError(error)) {
        console.error('Response status:', error.response?.status);
        console.error('Response data:', error.response?.data);
        console.error('Request headers:', error.config?.headers);
        throw new Error(`CodeSandbox API Error: ${error.response?.data?.message || error.response?.data?.error || error.message}`);
      }
      throw error;
    }
  }

  /**
   * Update an existing sandbox
   */
  async updateSandbox(sandboxId: string, files: { [path: string]: string }): Promise<void> {
    try {
      const sandboxFiles: SandboxFiles = {};
      
      for (const [path, content] of Object.entries(files)) {
        sandboxFiles[path] = {
          content,
          isBinary: false,
        };
      }

      await axios.patch(
        `${CODESANDBOX_API_URL}/sandboxes/${sandboxId}`,
        { files: sandboxFiles },
        { headers: this.headers }
      );
    } catch (error) {
      console.error('Error updating CodeSandbox:', error);
      if (axios.isAxiosError(error)) {
        throw new Error(`CodeSandbox API Error: ${error.response?.data?.message || error.message}`);
      }
      throw error;
    }
  }

  /**
   * Delete a sandbox
   */
  async deleteSandbox(sandboxId: string): Promise<void> {
    try {
      await axios.delete(
        `${CODESANDBOX_API_URL}/sandboxes/${sandboxId}`,
        { headers: this.headers }
      );
    } catch (error) {
      console.error('Error deleting CodeSandbox:', error);
      if (axios.isAxiosError(error)) {
        throw new Error(`CodeSandbox API Error: ${error.response?.data?.message || error.message}`);
      }
      throw error;
    }
  }

  /**
   * Get sandbox info
   */
  async getSandbox(sandboxId: string): Promise<any> {
    try {
      const response = await axios.get(
        `${CODESANDBOX_API_URL}/sandboxes/${sandboxId}`,
        { headers: this.headers }
      );
      return response.data;
    } catch (error) {
      console.error('Error getting CodeSandbox:', error);
      if (axios.isAxiosError(error)) {
        throw new Error(`CodeSandbox API Error: ${error.response?.data?.message || error.message}`);
      }
      throw error;
    }
  }

  /**
   * Get default package.json based on template
   */
  private getDefaultPackageJson(template: string, title?: string): any {
    const basePackage = {
      name: title?.toLowerCase().replace(/\s+/g, '-') || 'devmindx-project',
      version: '1.0.0',
      description: 'Generated by DevMindX AI',
      main: 'index.js',
      scripts: {},
      dependencies: {},
      devDependencies: {},
    };

    switch (template) {
      case 'react':
        return {
          ...basePackage,
          scripts: {
            start: 'react-scripts start',
            build: 'react-scripts build',
            test: 'react-scripts test',
            eject: 'react-scripts eject',
          },
          dependencies: {
            react: '^18.2.0',
            'react-dom': '^18.2.0',
            'react-scripts': '^5.0.1',
          },
        };

      case 'vue':
        return {
          ...basePackage,
          scripts: {
            serve: 'vue-cli-service serve',
            build: 'vue-cli-service build',
          },
          dependencies: {
            vue: '^3.3.0',
          },
          devDependencies: {
            '@vue/cli-service': '^5.0.0',
          },
        };

      case 'node':
        return {
          ...basePackage,
          scripts: {
            start: 'node index.js',
            dev: 'nodemon index.js',
          },
          dependencies: {
            express: '^4.18.0',
          },
          devDependencies: {
            nodemon: '^3.0.0',
          },
        };

      case 'vanilla':
        return {
          ...basePackage,
          scripts: {
            start: 'parcel index.html',
            build: 'parcel build index.html',
          },
          devDependencies: {
            parcel: '^2.9.0',
          },
        };

      default:
        return basePackage;
    }
  }

  /**
   * Detect template from files
   */
  detectTemplate(files: { [path: string]: string }): string {
    const fileNames = Object.keys(files);
    
    // Check for React
    if (fileNames.some(f => f.includes('jsx') || f.includes('tsx'))) {
      return 'react';
    }
    
    // Check for Vue
    if (fileNames.some(f => f.endsWith('.vue'))) {
      return 'vue';
    }
    
    // Check for Angular
    if (fileNames.some(f => f.includes('angular') || f.includes('ng'))) {
      return 'angular';
    }
    
    // Check for Node.js
    if (fileNames.some(f => f === 'server.js' || f === 'app.js')) {
      return 'node';
    }
    
    // Check for static HTML
    if (fileNames.some(f => f.endsWith('.html'))) {
      return 'static';
    }
    
    return 'vanilla';
  }
}

export default new CodeSandboxService();
