import React, { useState, useEffect, useRef } from 'react';
import { 
  Video, VideoOff, Mic, MicOff, Monitor, MonitorOff, 
  Phone, PhoneOff, Users, FileText,
  Download, Plus, X, Maximize2, Minimize2,
  Clock, User, File, Edit, Trash2
} from 'lucide-react';
import { useVideoCall } from '../hooks/use-video-call';
import type { MeetingData } from '../types/meeting';
import { Button } from './ui/button';
import { ScrollArea } from './ui/scroll-area';
import { Tabs, TabsContent, TabsList, TabsTrigger } from './ui/tabs';

// Simple PDF generation function (inline to avoid circular deps)
function generateMeetingPDF(meetingData: MeetingData): void {
  const formatDate = (date: Date) => new Date(date).toLocaleString();
  const duration = meetingData.endTime 
    ? Math.round((new Date(meetingData.endTime).getTime() - new Date(meetingData.startTime).getTime()) / 60000)
    : 'Ongoing';

  const html = `<!DOCTYPE html><html><head><title>Meeting Summary</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Segoe UI',Arial,sans-serif;padding:40px;max-width:800px;margin:0 auto;color:#333}h1{text-align:center;color:#1a1a2e;margin-bottom:10px}h2{text-align:center;color:#4a4a6a;margin-bottom:30px;font-weight:normal}h3{color:#1a1a2e;border-bottom:2px solid #6366f1;padding-bottom:8px;margin:25px 0 15px}.details{background:#f8f9fa;padding:20px;border-radius:8px;margin-bottom:20px}.details p{margin:8px 0}.participant{background:#fff;border:1px solid #e0e0e0;padding:12px;margin:8px 0;border-radius:6px}.note{background:#f0f0f5;padding:12px;margin:8px 0;border-radius:6px;border-left:4px solid #6366f1}.auto-note{border-left-color:#10b981;background:#ecfdf5}.footer{text-align:center;margin-top:40px;padding-top:20px;border-top:1px solid #eee;color:#999}@media print{body{padding:20px}}</style></head>
<body><h1>Meeting Summary Report</h1><h2>${meetingData.title}</h2>
<div class="details"><p><strong>Meeting ID:</strong> ${meetingData.id}</p><p><strong>Host:</strong> ${meetingData.hostName}</p><p><strong>Start:</strong> ${formatDate(meetingData.startTime)}</p><p><strong>End:</strong> ${meetingData.endTime ? formatDate(meetingData.endTime) : 'Ongoing'}</p><p><strong>Duration:</strong> ${typeof duration === 'number' ? duration + ' min' : duration}</p><p><strong>Participants:</strong> ${meetingData.participants.length}</p></div>
<h3>Participants</h3>${meetingData.participants.map(p => `<div class="participant"><strong>${p.username}</strong><br><small>Joined: ${formatDate(p.joinedAt)}${p.leftAt ? ' | Left: ' + formatDate(p.leftAt) : ''}</small></div>`).join('')}
${meetingData.fileActivities.length > 0 ? `<h3>File Activities</h3>${meetingData.fileActivities.map(a => `<div class="participant"><strong>${a.type.toUpperCase()}</strong>: ${a.fileName} by ${a.username}</div>`).join('')}` : ''}
${meetingData.notes.length > 0 ? `<h3>Notes</h3>${meetingData.notes.map(n => `<div class="note ${n.isAutoGenerated ? 'auto-note' : ''}"><small>${formatDate(n.timestamp)} - ${n.author}</small><p>${n.content}</p></div>`).join('')}` : ''}
<div class="footer">Generated by DevMindX - ${new Date().toLocaleString()}</div></body></html>`;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 500);
  }
}

interface VideoCallPanelProps { 
  sessionId: string | null;
  currentUserId: string;
  currentUsername: string;
  currentUserColor: string;
  isHost: boolean;
  onClose: () => void;
}

export function VideoCallPanel({
  sessionId,
  currentUserId,
  currentUsername,
  currentUserColor,
  isHost,
  onClose
}: VideoCallPanelProps) {
  const {
    localStream,
    screenStream,
    participants,
    isAudioEnabled,
    isVideoEnabled,
    isScreenSharing,
    isInCall,
    meetingData,
    localVideoRef,
    initializeMeeting,
    joinCall,
    leaveCall,
    endMeeting,
    toggleAudio,
    toggleVideo,
    startScreenShare,
    stopScreenShare,
    addNote,
    trackFileActivity
  } = useVideoCall(sessionId);

  const [isExpanded, setIsExpanded] = useState(false);
  const [activeTab, setActiveTab] = useState('video');
  const [newNote, setNewNote] = useState('');
  const [showParticipants, setShowParticipants] = useState(true);
  const remoteVideoRefs = useRef<Map<string, HTMLVideoElement>>(new Map());

  // Initialize meeting when component mounts (if host)
  useEffect(() => {
    if (isHost && !meetingData) {
      initializeMeeting(currentUserId, currentUsername, `Collaboration Session - ${new Date().toLocaleDateString()}`);
    }
  }, [isHost, meetingData, initializeMeeting, currentUserId, currentUsername]);

  // Update remote video elements when participants change
  useEffect(() => {
    participants.forEach((participant, id) => {
      if (participant.stream && id !== currentUserId) {
        const videoEl = remoteVideoRefs.current.get(id);
        if (videoEl && videoEl.srcObject !== participant.stream) {
          videoEl.srcObject = participant.stream;
        }
      }
    });
  }, [participants, currentUserId]);

  const handleJoinCall = async () => {
    try {
      await joinCall(currentUserId, currentUsername, currentUserColor);
    } catch (error) {
      console.error('Failed to join call:', error);
    }
  };

  const handleLeaveCall = () => {
    leaveCall(currentUserId, currentUsername);
  };

  const handleEndMeeting = () => {
    endMeeting();
    onClose();
  };

  const handleAddNote = () => {
    if (newNote.trim()) {
      addNote(newNote.trim(), currentUsername, currentUserId, false);
      setNewNote('');
    }
  };

  const handleDownloadPDF = () => {
    if (meetingData) {
      generateMeetingPDF(meetingData);
    }
  };

  const formatTime = (date: Date) => new Date(date).toLocaleTimeString();
  const formatDateTime = (date: Date) => new Date(date).toLocaleString();

  const participantArray = Array.from(participants.values());

  return (
    <div className={`fixed ${isExpanded ? 'inset-4' : 'bottom-4 right-4 w-96'} bg-gray-900 rounded-xl shadow-2xl border border-gray-700 z-50 flex flex-col transition-all duration-300`}>
      {/* Header */}
      <div className="flex items-center justify-between p-3 border-b border-gray-700 bg-gray-800 rounded-t-xl">
        <div className="flex items-center gap-2">
          <Video className="w-5 h-5 text-green-400" />
          <span className="font-semibold text-white">
            {meetingData?.title || 'Video Call'}
          </span>
          {isInCall && (
            <span className="flex items-center gap-1 text-xs text-green-400 bg-green-400/20 px-2 py-0.5 rounded-full">
              <span className="w-2 h-2 bg-green-400 rounded-full animate-pulse" />
              Live
            </span>
          )}
        </div>
        <div className="flex items-center gap-1">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setIsExpanded(!isExpanded)}
            className="text-gray-400 hover:text-white"
          >
            {isExpanded ? <Minimize2 className="w-4 h-4" /> : <Maximize2 className="w-4 h-4" />}
          </Button>
          <Button
            variant="ghost"
            size="sm"
            onClick={onClose}
            className="text-gray-400 hover:text-white"
          >
            <X className="w-4 h-4" />
          </Button>
        </div>
      </div>

      {/* Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col">
        <TabsList className="grid grid-cols-4 bg-gray-800 m-2 rounded-lg">
          <TabsTrigger value="video" className="text-xs">
            <Video className="w-3 h-3 mr-1" /> Video
          </TabsTrigger>
          <TabsTrigger value="participants" className="text-xs">
            <Users className="w-3 h-3 mr-1" /> ({participantArray.length})
          </TabsTrigger>
          <TabsTrigger value="notes" className="text-xs">
            <FileText className="w-3 h-3 mr-1" /> Notes
          </TabsTrigger>
          <TabsTrigger value="activity" className="text-xs">
            <File className="w-3 h-3 mr-1" /> Files
          </TabsTrigger>
        </TabsList>

        {/* Video Tab */}
        <TabsContent value="video" className="flex-1 p-2 m-0">
          <div className={`grid gap-2 h-full ${isExpanded ? 'grid-cols-3' : 'grid-cols-2'}`}>
            {/* Local Video */}
            <div className="relative bg-gray-800 rounded-lg overflow-hidden aspect-video">
              <video
                ref={localVideoRef}
                autoPlay
                muted
                playsInline
                className="w-full h-full object-cover"
              />
              {!isVideoEnabled && (
                <div className="absolute inset-0 flex items-center justify-center bg-gray-800">
                  <div className="w-16 h-16 rounded-full bg-gray-700 flex items-center justify-center">
                    <User className="w-8 h-8 text-gray-400" />
                  </div>
                </div>
              )}
              <div className="absolute bottom-2 left-2 bg-black/60 px-2 py-1 rounded text-xs text-white">
                You {isHost && '(Host)'}
              </div>
              {!isAudioEnabled && (
                <div className="absolute top-2 right-2 bg-red-500/80 p-1 rounded">
                  <MicOff className="w-3 h-3 text-white" />
                </div>
              )}
            </div>

            {/* Screen Share */}
            {screenStream && (
              <div className="relative bg-gray-800 rounded-lg overflow-hidden aspect-video col-span-2">
                <video
                  autoPlay
                  playsInline
                  ref={(el) => { if (el) el.srcObject = screenStream; }}
                  className="w-full h-full object-contain"
                />
                <div className="absolute bottom-2 left-2 bg-blue-500/80 px-2 py-1 rounded text-xs text-white flex items-center gap-1">
                  <Monitor className="w-3 h-3" /> Screen Share
                </div>
              </div>
            )}

            {/* Remote Participants */}
            {participantArray
              .filter(p => p.id !== currentUserId)
              .map(participant => (
                <div key={participant.id} className="relative bg-gray-800 rounded-lg overflow-hidden aspect-video">
                  <video
                    ref={(el) => { if (el) remoteVideoRefs.current.set(participant.id, el); }}
                    autoPlay
                    playsInline
                    className="w-full h-full object-cover"
                  />
                  {!participant.isVideoEnabled && (
                    <div className="absolute inset-0 flex items-center justify-center bg-gray-800">
                      <div 
                        className="w-16 h-16 rounded-full flex items-center justify-center text-white text-xl font-bold"
                        style={{ backgroundColor: participant.color }}
                      >
                        {participant.username.charAt(0).toUpperCase()}
                      </div>
                    </div>
                  )}
                  <div className="absolute bottom-2 left-2 bg-black/60 px-2 py-1 rounded text-xs text-white">
                    {participant.username}
                  </div>
                  {!participant.isAudioEnabled && (
                    <div className="absolute top-2 right-2 bg-red-500/80 p-1 rounded">
                      <MicOff className="w-3 h-3 text-white" />
                    </div>
                  )}
                </div>
              ))}
          </div>
        </TabsContent>

        {/* Participants Tab */}
        <TabsContent value="participants" className="flex-1 p-2 m-0">
          <ScrollArea className="h-full">
            <div className="space-y-2">
              {meetingData?.participants.map(participant => (
                <div 
                  key={participant.id}
                  className="flex items-center gap-3 p-3 bg-gray-800 rounded-lg"
                >
                  <div 
                    className="w-10 h-10 rounded-full flex items-center justify-center text-white font-bold"
                    style={{ backgroundColor: participant.color }}
                  >
                    {participant.username.charAt(0).toUpperCase()}
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-2">
                      <span className="text-white font-medium">{participant.username}</span>
                      {participant.id === meetingData.hostId && (
                        <span className="text-xs bg-yellow-500/20 text-yellow-400 px-2 py-0.5 rounded">Host</span>
                      )}
                      {!participant.leftAt && (
                        <span className="w-2 h-2 bg-green-400 rounded-full" />
                      )}
                    </div>
                    <div className="text-xs text-gray-400 mt-1">
                      <Clock className="w-3 h-3 inline mr-1" />
                      Joined: {formatTime(participant.joinedAt)}
                      {participant.leftAt && ` | Left: ${formatTime(participant.leftAt)}`}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </ScrollArea>
        </TabsContent>

        {/* Notes Tab */}
        <TabsContent value="notes" className="flex-1 p-2 m-0 flex flex-col">
          <div className="flex gap-2 mb-2">
            <input
              type="text"
              value={newNote}
              onChange={(e) => setNewNote(e.target.value)}
              onKeyPress={(e) => e.key === 'Enter' && handleAddNote()}
              placeholder="Add a note..."
              className="flex-1 bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-indigo-500"
            />
            <Button onClick={handleAddNote} size="sm" className="bg-indigo-600 hover:bg-indigo-700">
              <Plus className="w-4 h-4" />
            </Button>
          </div>
          <ScrollArea className="flex-1">
            <div className="space-y-2">
              {meetingData?.notes.map(note => (
                <div 
                  key={note.id}
                  className={`p-3 rounded-lg ${note.isAutoGenerated ? 'bg-gray-800/50 border-l-2 border-green-500' : 'bg-gray-800'}`}
                >
                  <div className="flex items-center justify-between mb-1">
                    <span className={`text-xs ${note.isAutoGenerated ? 'text-green-400' : 'text-indigo-400'}`}>
                      {note.isAutoGenerated ? '🤖 Auto' : '✏️ ' + note.author}
                    </span>
                    <span className="text-xs text-gray-500">{formatTime(note.timestamp)}</span>
                  </div>
                  <p className="text-sm text-gray-300">{note.content}</p>
                </div>
              ))}
            </div>
          </ScrollArea>
        </TabsContent>

        {/* File Activity Tab */}
        <TabsContent value="activity" className="flex-1 p-2 m-0">
          <ScrollArea className="h-full">
            <div className="space-y-2">
              {meetingData?.fileActivities.length === 0 ? (
                <div className="text-center text-gray-500 py-8">
                  <File className="w-12 h-12 mx-auto mb-2 opacity-50" />
                  <p>No file activities yet</p>
                </div>
              ) : (
                meetingData?.fileActivities.map(activity => (
                  <div key={activity.id} className="flex items-start gap-3 p-3 bg-gray-800 rounded-lg">
                    <div className={`p-2 rounded ${
                      activity.type === 'created' ? 'bg-green-500/20 text-green-400' :
                      activity.type === 'updated' ? 'bg-yellow-500/20 text-yellow-400' :
                      'bg-red-500/20 text-red-400'
                    }`}>
                      {activity.type === 'created' ? <Plus className="w-4 h-4" /> :
                       activity.type === 'updated' ? <Edit className="w-4 h-4" /> :
                       <Trash2 className="w-4 h-4" />}
                    </div>
                    <div className="flex-1">
                      <div className="text-sm text-white font-medium">{activity.fileName}</div>
                      <div className="text-xs text-gray-400">
                        {activity.type.charAt(0).toUpperCase() + activity.type.slice(1)} by {activity.username}
                      </div>
                      <div className="text-xs text-gray-500">{formatTime(activity.timestamp)}</div>
                    </div>
                  </div>
                ))
              )}
            </div>
          </ScrollArea>
        </TabsContent>
      </Tabs>

      {/* Control Bar */}
      <div className="p-3 border-t border-gray-700 bg-gray-800 rounded-b-xl">
        {!isInCall ? (
          <div className="flex justify-center gap-2">
            <Button
              onClick={handleJoinCall}
              className="bg-green-600 hover:bg-green-700 text-white px-6"
            >
              <Phone className="w-4 h-4 mr-2" />
              Join Call
            </Button>
          </div>
        ) : (
          <div className="flex items-center justify-between">
            <div className="flex gap-2">
              <Button
                variant="ghost"
                size="sm"
                onClick={toggleAudio}
                className={`${isAudioEnabled ? 'bg-gray-700 text-white' : 'bg-red-500/20 text-red-400'}`}
              >
                {isAudioEnabled ? <Mic className="w-4 h-4" /> : <MicOff className="w-4 h-4" />}
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={toggleVideo}
                className={`${isVideoEnabled ? 'bg-gray-700 text-white' : 'bg-red-500/20 text-red-400'}`}
              >
                {isVideoEnabled ? <Video className="w-4 h-4" /> : <VideoOff className="w-4 h-4" />}
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={isScreenSharing ? stopScreenShare : startScreenShare}
                className={`${isScreenSharing ? 'bg-blue-500/20 text-blue-400' : 'bg-gray-700 text-white'}`}
              >
                {isScreenSharing ? <MonitorOff className="w-4 h-4" /> : <Monitor className="w-4 h-4" />}
              </Button>
            </div>

            <div className="flex gap-2">
              {meetingData && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleDownloadPDF}
                  className="bg-indigo-500/20 text-indigo-400 hover:bg-indigo-500/30"
                  title="Download Meeting Summary PDF"
                >
                  <Download className="w-4 h-4 mr-1" />
                  PDF
                </Button>
              )}
              <Button
                variant="ghost"
                size="sm"
                onClick={handleLeaveCall}
                className="bg-red-500/20 text-red-400 hover:bg-red-500/30"
              >
                <PhoneOff className="w-4 h-4 mr-1" />
                Leave
              </Button>
              {isHost && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleEndMeeting}
                  className="bg-red-600 text-white hover:bg-red-700"
                >
                  End Meeting
                </Button>
              )}
            </div>
          </div>
        )}

        {/* Meeting Info */}
        {meetingData && (
          <div className="mt-2 pt-2 border-t border-gray-700 flex items-center justify-between text-xs text-gray-400">
            <span>
              <Clock className="w-3 h-3 inline mr-1" />
              Started: {formatDateTime(meetingData.startTime)}
            </span>
            <span>
              {meetingData.notes.length} notes | {meetingData.fileActivities.length} file changes
            </span>
          </div>
        )}
      </div>
    </div>
  );
}

export default VideoCallPanel;
